# Generated by Django 5.1.3 on 2024-11-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('tara', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PiataEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('pret_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Retea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('Stație Transformare', 'Stație Transformare'), ('Linie Înaltă Tensiune', 'Linie Înaltă Tensiune')], max_length=50)),
                ('locatie', models.CharField(max_length=100)),
                ('capacitate_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stare', models.CharField(choices=[('Operațional', 'Operațional'), ('Neoperațional', 'Neoperațional')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_tara', models.CharField(max_length=100)),
                ('cod_iso', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('Cumpărare', 'Cumpărare'), ('Vânzare', 'Vânzare')], max_length=20)),
                ('volum_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inceput', models.DateField(blank=True, null=True)),
                ('data_sfarsit', models.DateField(blank=True, null=True)),
                ('furnizor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.furnizor')),
                ('tara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tara')),
            ],
        ),
        migrations.CreateModel(
            name='FluxEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('volum_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contract')),
                ('retea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.retea')),
            ],
        ),
    ]
